### ISSUE TITLE
Lilygo T-Deck: I2C address is 0x5D, but reset is not connected

### ISSUE THREAD

**Issue by oschettler** [rgrizzell/CircuitPython_GT911#2]
Thank you for this beautiful library. However, I have a problem with the I2C addresses on the T-Deck. I am not entirely sure if this is the correct spot in [the schematic](https://github.com/Xinyuan-LilyGO/T-Deck/blob/master/schematic/schematic.pdf). If it is, then the reset pin for the touch device can't be controlled:
 
![Bildschirmfoto von 2024-04-28 22 40 57](https://github.com/rgrizzell/CircuitPython_GT911/assets/124634/4fa83040-eca5-44fe-8693-0ec939aeec8a)

This means, I can't set the rst_pin parameter in the constructor of the GP911 class as suggested in [your documentation](https://circuitpython-gt911.readthedocs.io/en/latest/api.html).

According to [the code](https://github.com/rgrizzell/CircuitPython_GT911/blob/main/gt911.py#L82), this means that the secondary address is chosen: 0x14. Unfortunately, the actual address should be 0x5D, at least for this board. 

Only when I swap the addresses in your code, I get the expected result, touches can be detected: 

![Bildschirmfoto von 2024-04-28 22 46 33](https://github.com/rgrizzell/CircuitPython_GT911/assets/124634/e7dc4e47-9473-44fc-93b1-e43d06a3dcef)

My touch.py contains the code from your https://github.com/rgrizzell/CircuitPython_GT911/blob/main/examples/gt911_simpletest.py

**Comment by rgrizzell** [comment]
@oschettler Thanks for raising this issue. This was something I observed with the T-Deck as well, but I chose to follow the [datasheet](https://www.distec.de/fileadmin/pdf/produkte/Touchcontroller/DDGroup/GT911_Datasheet.pdf) for the library implementation. In hindsight, that may have been foolish since the T-Deck was the only device I had to test with. The addressing could indeed be wrong. The screens are relatively inexpensive, so I will order one and re-validate the library.

Until then, I'll patch the library to allow for manually specifying the I2C address. Its probably better than coding around different circuit designs.
